/**
 * @file ephemeral.test.ts
 * @description Test suite for @centaury/ephemeral streaming parser, sanitizer & mounting engine
 */

import { describe, it, expect } from 'bun:test';
import { Window } from 'happy-dom';
import { EphemeralSanitizer } from '../src/sanitizer';
import { EphemeralStreamParser } from '../src/parser';
import { renderNodeToDOM, CentauryEphemeralElement, registerEphemeralComponents } from '../src/mount';

describe('@centaury/ephemeral Sanitizer & Security Policy', () => {
  it('allows approved UI component tags and standard HTML', () => {
    expect(EphemeralSanitizer.isTagAllowed('ui-card')).toBe(true);
    expect(EphemeralSanitizer.isTagAllowed('ui-button')).toBe(true);
    expect(EphemeralSanitizer.isTagAllowed('div')).toBe(true);
    expect(EphemeralSanitizer.isTagAllowed('svg')).toBe(true);
  });

  it('rejects dangerous tags strictly', () => {
    expect(EphemeralSanitizer.isTagAllowed('script')).toBe(false);
    expect(EphemeralSanitizer.isTagAllowed('iframe')).toBe(false);
    expect(EphemeralSanitizer.isTagAllowed('object')).toBe(false);
  });

  it('strips inline on* event handlers and javascript: URIs', () => {
    expect(EphemeralSanitizer.isAttrSafe('onclick', 'alert(1)')).toBe(false);
    expect(EphemeralSanitizer.isAttrSafe('onload', 'malicious()')).toBe(false);
    expect(EphemeralSanitizer.isAttrSafe('href', 'javascript:evil()')).toBe(false);
    expect(EphemeralSanitizer.isAttrSafe('title', 'Safe title text')).toBe(true);
    expect(EphemeralSanitizer.isAttrSafe('action', 'trigger_quarantine')).toBe(true);
  });
});

describe('@centaury/ephemeral Streaming Token Parser', () => {
  it('parses complete DSL markup into clean AST', () => {
    const markup = `
      <ui-card elevation="glass">
        <ui-header title="Live Threat Matrix" badge="critical" />
        <ui-metric value="99.4%" change="+0.2%" />
        <ui-button action="quarantine" param='{"id":"node-9"}'>Isolate Node</ui-button>
      </ui-card>
    `;

    const nodes = EphemeralStreamParser.parse(markup);
    expect(nodes.length).toBe(1);
    expect(nodes[0].tag).toBe('ui-card');
    expect(nodes[0].attrs.elevation).toBe('glass');
    expect(nodes[0].children.length).toBeGreaterThan(0);
  });

  it('handles chunk-by-chunk token streaming incrementally', () => {
    let mountedCount = 0;
    const parser = new EphemeralStreamParser((_node) => {
      mountedCount++;
    });

    // Feed chunks sequentially
    parser.write('<ui-');
    parser.write('card elevation="neon">');
    parser.write('<p>System Operational</p>');
    parser.write('</ui-card>');

    expect(mountedCount).toBe(1);
    expect(parser.rootNodes[0].attrs.elevation).toBe('neon');
  });
});

describe('@centaury/ephemeral DOM Mounting & Event Dispatching', () => {
  it('renders AST directly to DOM and dispatches ephemeral:action', () => {
    const window = new Window();
    const document = window.document;

    const astNode = {
      tag: 'ui-button',
      attrs: {
        action: 'deploy_patch',
        param: JSON.stringify({ version: '1.2.0' }),
      },
      children: ['Apply Patch Now'],
    };

    const domElement = renderNodeToDOM(astNode, document as unknown as Document) as HTMLElement;
    expect(domElement.tagName.toLowerCase()).toBe('ui-button');
    expect(domElement.textContent).toBe('Apply Patch Now');

    let actionFired = false;
    let actionDetail: any = null;

    domElement.addEventListener('ephemeral:action', (e: any) => {
      actionFired = true;
      actionDetail = e.detail;
    });

    domElement.dispatchEvent(new window.Event('click', { bubbles: true }) as unknown as Event);

    expect(actionFired).toBe(true);
    expect(actionDetail.action).toBe('deploy_patch');
    expect(actionDetail.param.version).toBe('1.2.0');
  });

  it('mounts dynamic UI incrementally into container with stream parser', () => {
    const window = new Window();
    const document = window.document;

    const host = document.createElement('div');
    const parser = new EphemeralStreamParser((node) => {
      host.appendChild(renderNodeToDOM(node, document as unknown as Document) as any);
    });

    parser.write('<ui-card elevation="glass"><p>Generated by Gemini 4 Pro</p></ui-card>');
    expect(host.querySelectorAll('ui-card').length).toBe(1);
    expect(host.textContent).toContain('Generated by Gemini 4 Pro');

    host.innerHTML = '';
    expect(host.innerHTML).toBe('');
  });
});
